### ISSUE TITLE
Rotation restarts the tapping process

### ISSUE THREAD

**Issue by BrownRiceRice** [jemitk/Pacer#3]
From Jemitk: "Every time the screen rotation is detected, it will start the onStart() method in that activity. Currently, the "let's start tapping!" screen will restart everytime I rotate the screen on the "tap the heart to the beat" one and restart the entire song library again. Has to be fixed!"

**Comment by jemitk** [comment]
http://stackoverflow.com/questions/6315908/which-activity-method-is-called-when-orientation-changes-occur

So it seems like it goes through onPause -> onSaveInstanceState -> onStop -> onCreate -> onStart -> onResume

**Comment by jemitk** [comment]
I was thinking about this for a while... and the simplist fix will be not allowing people to rotate the screen. This solution makes sense because probably it's not a great idea to rotate the screen while you are tapping to the songs. This solution might be the nice solution for us, the programmers mainly since we don't have to keep track of the songs that the users already tapped too.

**Comment by BrownRiceRice** [comment]
True.  It seems like bad coding practice, but it works. The only other arguments that I can think of are being able to re-start when the user leaves and then comes back, but even then, we'd want to start from scratch (maybe?)...  Apparently we can just mark the layout as only vertical, and that'll prevent it from changing, so I'll add that now.  

If we close this, we should figure out a way to deal with the song input better then. For people with 100's of songs, they'll have to stay on Pacer for a long time (~10-20minutes) without navigating away. I'm planning to refactor the BPMMusicFinderActivity for [issue 5](https://github.com/jemitk/Pacer/issues/5)  anyways, so maybe it'll turn out to be really easy to keep track of what they tapped after that.

**Comment by BrownRiceRice** [comment]
Tested, and the fix of adding "screenOrientation = "portrait"" works.  Do we want to call this closed for now, or should we start re-thinking our input on a larger scale here?

**Comment by BryceStevenWilley** [comment]
Calling closed for now. We have other things to worry about.
