### ISSUE TITLE
Workouts: increase and decrease song paces based on a predefined sequence

### ISSUE THREAD

**Issue by BrownRiceRice** [jemitk/Pacer#6]
The activity framework is already there, we just need to implement the logic. Last I remember, we discussed basing everything on the first bpm measurement, and then playing songs afterwards that were at defined intervals from each other. I.e, one workout could be [0, +5, +20, +30, +10, -10].  We could do some fancy stuff based on the length of each song chosen, but we can that add later. Nothing more concrete to add.

**Comment by BryceStevenWilley** [comment]
Added this functionality in [this commit](https://github.com/jemitk/Pacer/commit/dd8a3c2c6b1d696c3183c943e4dc1c62ebd4d549).  It's really buggy though, and most definitely is not ready for release. I'll make separate issues for each problem when we find it.
